name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # 6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libostree-dev flatpak-builder

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test
